set_property IOSTANDARD LVCMOS33 [get_ports {VGCLK_tri_o[0]}]
set_property PACKAGE_PIN B19 [get_ports {VGCLK_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RCLEAR_tri_o[0]}]
set_property PACKAGE_PIN C17 [get_ports {RCLEAR_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGDATEN_tri_o[0]}]
set_property PACKAGE_PIN C20 [get_ports {VGDATEN_tri_o[0]}]
set_property PACKAGE_PIN B20 [get_ports {VGSDATA_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGSDATA_tri_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc9226_data[0]}]
set_property PACKAGE_PIN Y10 [get_ports {adc9226_data[0]}]
set_property PACKAGE_PIN Y11 [get_ports {adc9226_data[1]}]
set_property PACKAGE_PIN W10 [get_ports {adc9226_data[2]}]
set_property PACKAGE_PIN W11 [get_ports {adc9226_data[3]}]
set_property PACKAGE_PIN U4 [get_ports {adc9226_data[4]}]
set_property PACKAGE_PIN T4 [get_ports {adc9226_data[5]}]
set_property PACKAGE_PIN U5 [get_ports {adc9226_data[6]}]
set_property PACKAGE_PIN U6 [get_ports {adc9226_data[7]}]
set_property PACKAGE_PIN U10 [get_ports {adc9226_data[8]}]
set_property PACKAGE_PIN R15 [get_ports {adc9226_data[9]}]
set_property PACKAGE_PIN U14 [get_ports {adc9226_data[10]}]
set_property PACKAGE_PIN U12 [get_ports {adc9226_data[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc9226_clk]
set_property PACKAGE_PIN U9 [get_ports adc9226_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {SW_15V_tri_o[0]}]
set_property PACKAGE_PIN L19 [get_ports {SW_15V_tri_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AD2_Addr_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD2_Addr_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD2_Addr_tri_io[0]}]
set_property PACKAGE_PIN G21 [get_ports {AD2_Addr_tri_io[0]}]
set_property PACKAGE_PIN F21 [get_ports {AD2_Addr_tri_io[1]}]
set_property PACKAGE_PIN F22 [get_ports {AD2_Addr_tri_io[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AD2_Convent_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD2_EOC_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD2_RD_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD3_Convent_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD3_EOC_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD3_RD_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Addr_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Addr_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_WR_tri_io[0]}]
set_property PACKAGE_PIN C22 [get_ports {AD2_Convent_tri_io[0]}]
set_property PACKAGE_PIN J22 [get_ports {AD2_EOC_tri_io[0]}]
set_property PACKAGE_PIN D22 [get_ports {AD2_RD_tri_io[0]}]
set_property PACKAGE_PIN D21 [get_ports {AD3_Convent_tri_io[0]}]
set_property PACKAGE_PIN G20 [get_ports {AD3_EOC_tri_io[0]}]
set_property PACKAGE_PIN E21 [get_ports {AD3_RD_tri_io[0]}]
set_property PACKAGE_PIN AB21 [get_ports {DA1_Addr_tri_io[0]}]
set_property PACKAGE_PIN AA18 [get_ports {DA1_Addr_tri_io[1]}]
set_property PACKAGE_PIN Y18 [get_ports {DA1_WR_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7226_DAC_tri_io[0]}]

set_property PACKAGE_PIN W12 [get_ports {AD7226_DAC_tri_io[0]}]
set_property PACKAGE_PIN AB20 [get_ports {AD7226_DAC_tri_io[1]}]
set_property PACKAGE_PIN AB19 [get_ports {AD7226_DAC_tri_io[2]}]
set_property PACKAGE_PIN V10 [get_ports {AD7226_DAC_tri_io[3]}]
set_property PACKAGE_PIN V9 [get_ports {AD7226_DAC_tri_io[4]}]
set_property PACKAGE_PIN W21 [get_ports {AD7226_DAC_tri_io[5]}]
set_property PACKAGE_PIN W20 [get_ports {AD7226_DAC_tri_io[6]}]
set_property PACKAGE_PIN W22 [get_ports {AD7226_DAC_tri_io[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD7829_1_2_ADC_tri_io[0]}]
set_property PACKAGE_PIN A16 [get_ports {AD7829_1_2_ADC_tri_io[0]}]
set_property PACKAGE_PIN A17 [get_ports {AD7829_1_2_ADC_tri_io[1]}]
set_property PACKAGE_PIN A18 [get_ports {AD7829_1_2_ADC_tri_io[2]}]
set_property PACKAGE_PIN A19 [get_ports {AD7829_1_2_ADC_tri_io[3]}]
set_property PACKAGE_PIN A21 [get_ports {AD7829_1_2_ADC_tri_io[4]}]
set_property PACKAGE_PIN A22 [get_ports {AD7829_1_2_ADC_tri_io[5]}]
set_property PACKAGE_PIN B22 [get_ports {AD7829_1_2_ADC_tri_io[6]}]
set_property PACKAGE_PIN B21 [get_ports {AD7829_1_2_ADC_tri_io[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AD9226_Buff_En_tri_io[0]}]
set_property PACKAGE_PIN V8 [get_ports {AD9226_Buff_En_tri_io[0]}]

set_property PACKAGE_PIN D20 [get_ports LASEL_Out]
set_property IOSTANDARD LVCMOS33 [get_ports LASEL_Out]
set_property PACKAGE_PIN D18 [get_ports LTRIG_Out]
set_property IOSTANDARD LVCMOS33 [get_ports LTRIG_Out]
