# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/maincontrol.xdc

# Block Designs: bd/main_control/main_control.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control || ORIG_REF_NAME==main_control} -quiet] -quiet

# IP: bd/main_control/ip/main_control_processing_system7_0_0/main_control_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_processing_system7_0_0 || ORIG_REF_NAME==main_control_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_0/main_control_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_0 || ORIG_REF_NAME==main_control_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_ps7_0_axi_periph_0/main_control_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_ps7_0_axi_periph_0 || ORIG_REF_NAME==main_control_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_rst_ps7_0_50M_0/main_control_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_rst_ps7_0_50M_0 || ORIG_REF_NAME==main_control_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_xbar_0/main_control_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_xbar_0 || ORIG_REF_NAME==main_control_xbar_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_1/main_control_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_1 || ORIG_REF_NAME==main_control_axi_gpio_0_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_2/main_control_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_2 || ORIG_REF_NAME==main_control_axi_gpio_0_2} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_gpio_0_3/main_control_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_gpio_0_3 || ORIG_REF_NAME==main_control_axi_gpio_0_3} -quiet] -quiet

# IP: bd/main_control/ip/main_control_ad9226_sample_0_0/main_control_ad9226_sample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_ad9226_sample_0_0 || ORIG_REF_NAME==main_control_ad9226_sample_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_dma_0_0/main_control_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_dma_0_0 || ORIG_REF_NAME==main_control_axi_dma_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_xbar_1/main_control_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_xbar_1 || ORIG_REF_NAME==main_control_xbar_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_axi_interconnect_0_0/main_control_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_axi_interconnect_0_0 || ORIG_REF_NAME==main_control_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_rst_ps7_0_40M_0/main_control_rst_ps7_0_40M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_rst_ps7_0_40M_0 || ORIG_REF_NAME==main_control_rst_ps7_0_40M_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_rst_ps7_0_142M_1/main_control_rst_ps7_0_142M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_rst_ps7_0_142M_1 || ORIG_REF_NAME==main_control_rst_ps7_0_142M_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_VGSDATA_0/main_control_VGSDATA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_VGSDATA_0 || ORIG_REF_NAME==main_control_VGSDATA_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_VGCLK_0/main_control_VGCLK_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_VGCLK_0 || ORIG_REF_NAME==main_control_VGCLK_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_AD2_Addr_0/main_control_AD2_Addr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_AD2_Addr_0 || ORIG_REF_NAME==main_control_AD2_Addr_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_DA1_Addr_0/main_control_DA1_Addr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_DA1_Addr_0 || ORIG_REF_NAME==main_control_DA1_Addr_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_DA1_WR_0/main_control_DA1_WR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_DA1_WR_0 || ORIG_REF_NAME==main_control_DA1_WR_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_DA1_WR_1/main_control_DA1_WR_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_DA1_WR_1 || ORIG_REF_NAME==main_control_DA1_WR_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_DA1_WR_2/main_control_DA1_WR_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_DA1_WR_2 || ORIG_REF_NAME==main_control_DA1_WR_2} -quiet] -quiet

# IP: bd/main_control/ip/main_control_DA1_WR_3/main_control_DA1_WR_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_DA1_WR_3 || ORIG_REF_NAME==main_control_DA1_WR_3} -quiet] -quiet

# IP: bd/main_control/ip/main_control_DA1_WR_4/main_control_DA1_WR_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_DA1_WR_4 || ORIG_REF_NAME==main_control_DA1_WR_4} -quiet] -quiet

# IP: bd/main_control/ip/main_control_AD3_RD_0/main_control_AD3_RD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_AD3_RD_0 || ORIG_REF_NAME==main_control_AD3_RD_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_AD2_RD_0/main_control_AD2_RD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_AD2_RD_0 || ORIG_REF_NAME==main_control_AD2_RD_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_AD2_RD_2/main_control_AD2_RD_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_AD2_RD_2 || ORIG_REF_NAME==main_control_AD2_RD_2} -quiet] -quiet

# IP: bd/main_control/ip/main_control_AD2_Convent_0/main_control_AD2_Convent_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_AD2_Convent_0 || ORIG_REF_NAME==main_control_AD2_Convent_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_ax_pwm_0_1/main_control_ax_pwm_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_ax_pwm_0_1 || ORIG_REF_NAME==main_control_ax_pwm_0_1} -quiet] -quiet

# IP: bd/main_control/ip/main_control_tier2_xbar_0_0/main_control_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_tier2_xbar_0_0 || ORIG_REF_NAME==main_control_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_tier2_xbar_1_0/main_control_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_tier2_xbar_1_0 || ORIG_REF_NAME==main_control_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_tier2_xbar_2_0/main_control_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_tier2_xbar_2_0 || ORIG_REF_NAME==main_control_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_auto_pc_0/main_control_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_auto_pc_0 || ORIG_REF_NAME==main_control_auto_pc_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_auto_us_0/main_control_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_auto_us_0 || ORIG_REF_NAME==main_control_auto_us_0} -quiet] -quiet

# IP: bd/main_control/ip/main_control_auto_pc_1/main_control_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_control_auto_pc_1 || ORIG_REF_NAME==main_control_auto_pc_1} -quiet] -quiet

# XDC: bd/main_control/main_control_ooc.xdc
